server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    add_header Strict-Transport-Security "max-age=63072000" always;

    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self';
        style-src 'self' 'unsafe-inline';
        img-src 'self' data: https://tiles.openfreemap.org;
        connect-src 'self' https://earthquake.usgs.gov https://tiles.openfreemap.org;
        worker-src 'self' blob:;
        font-src 'self';
    " always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
